[colors]
alpha=0.9
background=1a1a1a
foreground=ffffff

## Normal colors
regular0=1a1a1a
regular1=e63946
regular2=2ecc71
regular3=f1c40f
regular4=3498db
regular5=9b59b6
regular6=1abc9c
regular7=ffffff

##Bright colors
bright0=666666
bright1=ff4d4d
bright7=ffffff

##[cursor]
cursor=1a1a1a e63946

##[csd]
##border-width=2
##border-color=fffbflc7
